language: python
python:
    - 3.6
services:
    - mysql
install:
    - pip install -r requirements.txt
before_script:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
    - mysql -e "use mysql; update user set authentication_string=PASSWORD('password') where User='root'; update user set plugin='password';FLUSH PRIVILEGES;"
    - mysql_upgrade --user=root --password=PASSWORD
    - service mysql restart
script:
    - python manage.py test
notifications:
    slack: yiconfirmed:Y9HLCvmAzM2B35cZEiyU9bwd
    on_success: change
    on_failure: always