language: python
python:
    - 3.6
services:
    - mysql
install:
    - pip install -r requirements.txt
addons:
    apt:
        sources:
            - mysql-5.7-trusty
        packages:
            - mysql-server
            - mysql-client
before_script:
    - mysql --version
    - python --version
    - mysql -e 'CREATE DATABASE IF NOT EXISTS mediconnect;'
    - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    - sudo mysql_upgrade --port=3306 --user=root --password=password
    - sudo service mysql restart
script:
    - cp backend/constant.py.template backend/constant.py
    - python manage.py makemigrations
    - python manage.py migrate 
    - python manage.py test
notifications:
    slack: yiconfirmed:Y9HLCvmAzM2B35cZEiyU9bwd
    on_success: change
    on_failure: always
