language: python

python:
    - 3.6

install:
    - pip install -r requirements.txt

script:
    - python manage.py test

notifications:
    slack: yiconfirmed:Y9HLCvmAzM2B35cZEiyU9bwd
    on_success: change
    on_failure: always