# Generated by Django 2.1.2 on 2018-11-09 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import document.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=document.models.res_directory_path)),
                ('obsolete', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(0, 'ORIGINAL'), (1, 'C2E_TRANSLATED'), (2, 'FEEDBACK'), (3, 'E2C_TRANSLATED')], default=0)),
                ('extensions', models.TextField(blank=True, max_length=100, null=True)),
                ('limit', models.IntegerField(default=16384)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'db_document',
            },
        ),
    ]
