# Generated by Django 2.0.2 on 2018-11-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_resid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='resid',
            new_name='res',
        ),
    ]
