# Generated by Django 2.0.2 on 2018-03-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
    ]
