# Generated by Django 2.1.2 on 2018-11-16 19:15

from django.db import migrations, models
import django.db.models.deletion
import questionnaire.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('hospital', '0001_initial'),
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=500)),
                ('is_translated', models.BooleanField(default=False)),
                ('origin', models.FileField(null=True, upload_to=questionnaire.models.origin_questions_path)),
                ('translated', models.FileField(null=True, upload_to=questionnaire.models.translated_questions_path)),
            ],
            options={
                'db_table': 'db_answer',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'db_choice',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.IntegerField(choices=[(1, 'Multiple Choice'), (2, 'All that Matched'), (3, 'Short Answer')])),
                ('content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'db_question',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('is_translated', models.BooleanField(default=False)),
                ('origin', models.FileField(null=True, upload_to=questionnaire.models.origin_questions_path)),
                ('translated', models.FileField(null=True, upload_to=questionnaire.models.translated_questions_path)),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disease.Disease')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Hospital')),
                ('translator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Translator')),
            ],
            options={
                'db_table': 'db_questionnaire',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.Questionnaire'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.Questionnaire'),
        ),
    ]
