# Generated by Django 2.0.2 on 2018-09-26 00:40

from django.db import migrations, models
import django.db.models.deletion
import questionnaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('selected', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'db_choice',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.IntegerField(choices=[('Multiple Choice', 1), ('All that Matched', 2), ('Short Answer', 3)])),
                ('content', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'db_question',
            },
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='origin_pdf_path',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='questions_path',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='origin_pdf',
            field=models.FileField(null=True, upload_to=questionnaire.models.questions_path),
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.Questionnaire'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.Question'),
        ),
    ]
