# Generated by Django 2.0.2 on 2018-10-25 02:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20180810_0119'),
        ('questionnaire', '0005_auto_20181024_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=500)),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.Choice')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.Question')),
                ('res_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.Reservation')),
            ],
        ),
    ]
