# Generated by Django 2.0.2 on 2018-11-03 01:19

from django.db import migrations, models
import django.db.models.deletion
import questionnaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('questionnaire', '0006_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_translated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='origin',
            field=models.FileField(null=True, upload_to=questionnaire.models.origin_questions_path),
        ),
        migrations.AddField(
            model_name='answer',
            name='questionnaire_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.Questionnaire'),
        ),
        migrations.AddField(
            model_name='answer',
            name='translated',
            field=models.FileField(null=True, upload_to=questionnaire.models.translated_questions_path),
        ),
        migrations.AddField(
            model_name='answer',
            name='translator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Translator'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='origin',
            field=models.FileField(null=True, upload_to=questionnaire.models.origin_questions_path),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='translated',
            field=models.FileField(null=True, upload_to=questionnaire.models.translated_questions_path),
        ),
        migrations.AlterModelTable(
            name='answer',
            table='db_answer',
        ),
    ]
