# Generated by Django 2.1.2 on 2018-11-09 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name_pinyin', models.CharField(max_length=50)),
                ('last_name_pinyin', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(0, 'M'), (1, 'F'), (2, 'O')], default=0)),
                ('birthdate', models.DateField()),
                ('relationship', models.IntegerField(choices=[(0, 'SELF'), (1, 'RELATIVE'), (2, 'OTHER')], default=0)),
                ('passport', models.CharField(max_length=20)),
                ('notes', models.CharField(blank=True, max_length=10000)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
            ],
            options={
                'db_table': 'db_patient',
            },
        ),
    ]
