# Generated by Django 2.1.3 on 2018-11-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Male', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='relationship',
            field=models.CharField(choices=[('SELF', 'Self'), ('RELATIVE', 'Relative'), ('OTHER', 'Other')], default='Self', max_length=50),
        ),
    ]
