# Generated by Django 2.1.2 on 2018-11-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='relationship',
            field=models.IntegerField(),
        ),
    ]
