# Generated by Django 2.1.2 on 2018-11-16 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('hospital', '0001_initial'),
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default=0)),
                ('deposit', models.IntegerField(default=10000)),
                ('full_price', models.IntegerField(default=100000)),
                ('description', models.TextField(default='information')),
                ('feedback_time', models.IntegerField(default=1)),
                ('average_score', models.FloatField(default=0.0)),
                ('review_number', models.IntegerField(default=0)),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_price', to='disease.Disease')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_price', to='hospital.Hospital')),
            ],
            options={
                'db_table': 'db_info',
            },
        ),
        migrations.CreateModel(
            name='InfoReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=500, null=True)),
                ('score', models.IntegerField(null=True)),
                ('review_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
                ('info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Info')),
            ],
            options={
                'db_table': 'db_info_review',
            },
        ),
        migrations.CreateModel(
            name='LikeInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('like_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
                ('info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Info')),
            ],
            options={
                'db_table': 'db_like_info',
            },
        ),
    ]
