# Generated by Django 2.1.2 on 2018-11-09 01:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default=0)),
                ('deposit', models.IntegerField(default=10000)),
                ('full_price', models.IntegerField(default=100000)),
                ('description', models.TextField(default='information')),
                ('feedback_time', models.IntegerField(default=1)),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_price', to='disease.Disease')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_price', to='hospital.Hospital')),
            ],
            options={
                'db_table': 'db_info',
            },
        ),
    ]
