# Generated by Django 2.0.2 on 2018-11-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
