# Generated by Django 2.1.3 on 2018-11-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20181107_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='feedback_time',
            field=models.IntegerField(default=1),
        ),
    ]
