# Generated by Django 2.1.3 on 2018-11-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_info_feedback_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='deposit',
            field=models.FloatField(default=10000),
        ),
        migrations.AlterField(
            model_name='info',
            name='full_price',
            field=models.FloatField(default=100000),
        ),
    ]
