# Generated by Django 2.0.2 on 2018-09-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='default_availability',
            field=models.IntegerField(default=20),
        ),
    ]
