# Generated by Django 2.1.2 on 2018-11-16 19:15

from django.db import migrations, models
import hospital.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to=hospital.models.hospital_directory_path)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('overall_rank', models.IntegerField(default=0)),
                ('website', models.URLField(blank=True)),
                ('introduction', models.TextField(default='intro')),
                ('specialty', models.TextField(default='specialty')),
                ('average_score', models.FloatField(default=0.0)),
                ('review_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'db_hospital',
            },
        ),
    ]
