# Generated by Django 2.0.2 on 2018-11-04 21:21

from django.db import migrations, models
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalreview',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='hospitalreview',
            old_name='hospital_id',
            new_name='hospital',
        ),
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(null=True, upload_to=hospital.models.hospital_directory_path),
        ),
    ]
