# Generated by Django 2.1.3 on 2018-11-08 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0004_auto_20181107_2159'),
        ('hospital', '0002_auto_20181104_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='feedback_time',
        ),
        migrations.AddField(
            model_name='hospitalreview',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disease.Disease'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
    ]
