# Generated by Django 2.1.2 on 2018-11-09 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('keyword', models.CharField(default='unknown', max_length=150)),
                ('full_name', models.CharField(default='unknown', max_length=100)),
                ('name_eng', models.CharField(default='unknown', max_length=150)),
                ('types', models.CharField(default='unknwon', max_length=150)),
                ('target_group', models.CharField(default='unknown', max_length=150)),
                ('introduction', models.CharField(default='unknown', max_length=150)),
                ('categories', models.CharField(default='unknown', max_length=150)),
            ],
            options={
                'db_table': 'db_disease',
            },
        ),
    ]
