# Generated by Django 2.0.2 on 2018-11-08 02:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_auto_20181107_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='id',
            field=models.UUIDField(default=uuid.UUID('82aa30c6-27b3-4fb9-98a4-7cda33bb934f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
