# Generated by Django 2.1.3 on 2018-11-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0004_auto_20181107_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='categories',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='disease',
            name='full_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='disease',
            name='introduction',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='disease',
            name='name_eng',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='disease',
            name='target_group',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='disease',
            name='types',
            field=models.CharField(default='unknwon', max_length=150),
        ),
    ]
